# Generated by Django 5.2 on 2025-04-22 07:42

import cloudinary.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socialnetwork', '0002_postimage_user_avatar_alumni_post_teacher'),
    ]

    operations = [
        migrations.AddField(
            model_name='postimage',
            name='image',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='Post Image'),
        ),
        migrations.AddField(
            model_name='postimage',
            name='post',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='socialnetwork.post'),
        ),
    ]
