# Generated by Django 5.2 on 2025-04-22 07:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('socialnetwork', '0003_postimage_image_postimage_post'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='postimage',
            name='post',
        ),
    ]
