# Generated by Django 5.2 on 2025-04-23 08:40

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socialnetwork', '0005_surveypost_postimage_post_comment_group_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='cover',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='cover'),
        ),
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.IntegerField(choices=[(0, 'Admin'), (1, 'Alumni'), (2, 'Teacher')], default=0),
        ),
    ]
