# Generated by Django 5.2 on 2025-04-25 15:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socialnetwork', '0006_user_cover_user_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventInvitePost',
            fields=[
                ('post_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='socialnetwork.post')),
                ('title', models.CharField(max_length=255)),
                ('send_to_all', models.BooleanField(default=False)),
                ('groups', models.ManyToManyField(blank=True, to='socialnetwork.group')),
                ('individuals', models.ManyToManyField(blank=True, related_name='event_invites', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-id'],
                'abstract': False,
            },
            bases=('socialnetwork.post',),
        ),
    ]
