# Generated by Django 5.2 on 2025-04-26 06:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('socialnetwork', '0007_alter_user_options_alter_user_email_invitationpost'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='look_comment',
            new_name='lock_comment',
        ),
    ]
