# Generated by Django 5.2 on 2025-04-26 07:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('socialnetwork', '0008_rename_look_comment_post_lock_comment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='surveypost',
            old_name='end_timme',
            new_name='end_time',
        ),
    ]
