# Generated by Django 5.2 on 2025-04-26 07:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('socialnetwork', '0009_rename_end_timme_surveypost_end_time'),
    ]

    operations = [
        migrations.RenameField(
            model_name='surveypost',
            old_name='servey_type',
            new_name='survey_type',
        ),
    ]
