# Generated by Django 5.2 on 2025-04-26 10:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('socialnetwork', '0007_eventinvitepost'),
        ('socialnetwork', '0010_rename_servey_type_surveypost_survey_type'),
    ]

    operations = [
    ]
