# Generated by Django 5.2 on 2025-04-26 11:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('socialnetwork', '0011_merge_20250426_1102'),
        ('socialnetwork', '0011_merge_20250426_1758'),
    ]

    operations = [
    ]
