# Generated by Django 5.2 on 2025-04-26 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socialnetwork', '0012_merge_20250426_1815'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='lock_comment',
            field=models.BooleanField(default=False),
        ),
        migrations.DeleteModel(
            name='InvitationPost',
        ),
    ]
