# Generated by Django 5.2 on 2025-04-27 05:16

import cloudinary.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socialnetwork', '0013_alter_post_lock_comment_delete_invitationpost'),
    ]

    operations = [
        migrations.RenameField(
            model_name='alumni',
            old_name='mssv',
            new_name='student_code',
        ),
        migrations.AlterField(
            model_name='postimage',
            name='post',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='socialnetwork.post'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='surveypost',
            name='survey_type',
            field=models.IntegerField(choices=[(1, 'Training program'), (2, 'Recruitment information'), (3, 'Income'), (4, 'Employment situation')], default=1),
        ),
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=cloudinary.models.CloudinaryField(default='https://res.cloudinary.com/dqw4mc8dg/image/upload/v1737620154/aj6sc6isvelwkotlo1vw_zxmebm_nbsj9i.png', max_length=255, verbose_name='avatar'),
        ),
        migrations.CreateModel(
            name='InvitationPost',
            fields=[
                ('post_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='socialnetwork.post')),
                ('event_name', models.CharField(max_length=255)),
                ('groups', models.ManyToManyField(blank=True, to='socialnetwork.group')),
                ('users', models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-id'],
                'abstract': False,
            },
            bases=('socialnetwork.post',),
        ),
        migrations.DeleteModel(
            name='EventInvitePost',
        ),
    ]
