# Generated by Django 5.2 on 2025-05-03 08:38

import cloudinary.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socialnetwork', '0014_rename_mssv_alumni_student_code_alter_postimage_post_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='alumni',
            old_name='student_code',
            new_name='mssv',
        ),
        migrations.AlterField(
            model_name='postimage',
            name='post',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='socialnetwork.post'),
        ),
        migrations.AlterField(
            model_name='surveypost',
            name='survey_type',
            field=models.IntegerField(choices=[(1, 'Training program'), (2, 'Recruitment needs'), (3, 'Income'), (4, 'Employment status of alumni')], default=1),
        ),
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=cloudinary.models.CloudinaryField(default='null', max_length=255, verbose_name='avatar'),
        ),
        migrations.CreateModel(
            name='EventInvitePost',
            fields=[
                ('post_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='socialnetwork.post')),
                ('title', models.CharField(max_length=255)),
                ('send_to_all', models.BooleanField(default=False)),
                ('groups', models.ManyToManyField(blank=True, to='socialnetwork.group')),
                ('individuals', models.ManyToManyField(blank=True, related_name='event_invites', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-id'],
                'abstract': False,
            },
            bases=('socialnetwork.post',),
        ),
        migrations.DeleteModel(
            name='InvitationPost',
        ),
    ]
