# Generated by Django 5.2 on 2025-05-09 08:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('socialnetwork', '0002_auto_migrate_chatroom'),
        ('socialnetwork', '0016_chatroom_message'),
    ]

    operations = [
    ]
