# Generated by Django 5.2 on 2025-05-09 08:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('socialnetwork', '0017_merge_20250509_0809'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chatroom',
            options={},
        ),
    ]
