# Generated by Django 5.2 on 2025-05-13 14:10

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socialnetwork', '0018_alter_chatroom_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='users',
            field=models.ManyToManyField(blank=True, related_name='my_groups', to=settings.AUTH_USER_MODEL),
        ),
    ]
