# Generated by Django 5.2 on 2025-05-30 09:05

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('socialnetwork', '0019_alter_group_users'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=cloudinary.models.CloudinaryField(default='../static/image_default/alumni.png', max_length=255, verbose_name='avatar'),
        ),
    ]
